# Generated by Django 5.1.7 on 2025-03-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_Cliente', models.CharField(max_length=8)),
                ('nom_Cliente', models.CharField(max_length=25)),
                ('email_Cliente', models.CharField(max_length=50)),
                ('monto_Cliente', models.FloatField()),
                ('tlf_Cliente', models.IntegerField(verbose_name=9)),
            ],
        ),
    ]
