# Generated by Django 5.1.7 on 2025-03-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email_Cliente',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='monto_Cliente',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tlf_Cliente',
            field=models.CharField(max_length=9),
        ),
    ]
