# Generated by Django 5.1.7 on 2025-03-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClientes', '0002_alter_clientes_email_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='dni_Cliente',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
